language: python

env:
  - BUILD=tests
  - BUILD=docs

python:
  - "2.6"
  - "2.7"

install:
  - if [[ $BUILD == 'tests' ]]; then make init;  fi
  - if [[ $BUILD == 'docs' ]]; then make docs-init;  fi

script:
  - if [[ $BUILD == 'tests' ]]; then make test;  fi
  - if [[ $BUILD == 'docs' ]]; then make docs;  fi
